//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterLibrary.Models.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAPSACH
    {
        public int IDNHAP { get; set; }
        public Nullable<int> IDSACH { get; set; }
        public string TENSACH { get; set; }
        public Nullable<decimal> GIANHAP { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public System.DateTime NGNHAP { get; set; }
    }
}
